# Generated by Django 5.0.11 on 2025-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_token',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
